#!/usr/bin/env bash

function createRbi() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/Rbi.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/Rbi.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca-Rbi --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-Rbi.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-Rbi.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-Rbi.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca-Rbi.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/Rbi.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy Rbi's CA cert to Rbi's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/Rbi.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem" "${PWD}/organizations/peerOrganizations/Rbi.example.com/msp/tlscacerts/ca.crt"

  # Copy Rbi's CA cert to Rbi's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/Rbi.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem" "${PWD}/organizations/peerOrganizations/Rbi.example.com/tlsca/tlsca.Rbi.example.com-cert.pem"

  # Copy Rbi's CA cert to Rbi's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/Rbi.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem" "${PWD}/organizations/peerOrganizations/Rbi.example.com/ca/ca.Rbi.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-Rbi --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-Rbi --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-Rbi --id.name Rbiadmin --id.secret Rbiadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-Rbi -M "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/Rbi.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca-Rbi -M "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls" --enrollment.profile tls --csr.hosts peer0.Rbi.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/Rbi.example.com/peers/peer0.Rbi.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca-Rbi -M "${PWD}/organizations/peerOrganizations/Rbi.example.com/users/User1@Rbi.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/Rbi.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/Rbi.example.com/users/User1@Rbi.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://Rbiadmin:Rbiadminpw@localhost:7054 --caname ca-Rbi -M "${PWD}/organizations/peerOrganizations/Rbi.example.com/users/Admin@Rbi.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/Rbi/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/Rbi.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/Rbi.example.com/users/Admin@Rbi.example.com/msp/config.yaml"
}

function createHdfc() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/Hdfc.example.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/Hdfc.example.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca-Hdfc --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-Hdfc.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-Hdfc.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-Hdfc.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca-Hdfc.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/Hdfc.example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy Hdfc's CA cert to Hdfc's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/Hdfc.example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem" "${PWD}/organizations/peerOrganizations/Hdfc.example.com/msp/tlscacerts/ca.crt"

  # Copy Hdfc's CA cert to Hdfc's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/Hdfc.example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem" "${PWD}/organizations/peerOrganizations/Hdfc.example.com/tlsca/tlsca.Hdfc.example.com-cert.pem"

  # Copy Hdfc's CA cert to Hdfc's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/Hdfc.example.com/ca"
  cp "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem" "${PWD}/organizations/peerOrganizations/Hdfc.example.com/ca/ca.Hdfc.example.com-cert.pem"

  infoln "Registering peer0"
  set -x
  fabric-ca-client register --caname ca-Hdfc --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering user"
  set -x
  fabric-ca-client register --caname ca-Hdfc --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca-Hdfc --id.name Hdfcadmin --id.secret Hdfcadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-Hdfc -M "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/Hdfc.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/msp/config.yaml"

  infoln "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca-Hdfc -M "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls" --enrollment.profile tls --csr.hosts peer0.Hdfc.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/Hdfc.example.com/peers/peer0.Hdfc.example.com/tls/server.key"

  infoln "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca-Hdfc -M "${PWD}/organizations/peerOrganizations/Hdfc.example.com/users/User1@Hdfc.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/Hdfc.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/Hdfc.example.com/users/User1@Hdfc.example.com/msp/config.yaml"

  infoln "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://Hdfcadmin:Hdfcadminpw@localhost:8054 --caname ca-Hdfc -M "${PWD}/organizations/peerOrganizations/Hdfc.example.com/users/Admin@Hdfc.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/Hdfc/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/Hdfc.example.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/Hdfc.example.com/users/Admin@Hdfc.example.com/msp/config.yaml"
}

function createOrderer() {
  infoln "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/example.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/example.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/msp/tlscacerts/tlsca.example.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem"

# Loop through each orderer (orderer, orderer2, orderer3, orderer4) to register and generate artifacts
  for ORDERER in orderer orderer2 orderer3 orderer4; do
    infoln "Registering ${ORDERER}"
    set -x
    fabric-ca-client register --caname ca-orderer --id.name ${ORDERER} --id.secret ${ORDERER}pw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    infoln "Generating the ${ORDERER} MSP"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/config.yaml"

    # Workaround: Rename the signcert file to ensure consistency with Cryptogen generated artifacts
    mv "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/signcerts/cert.pem" "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/signcerts/${ORDERER}.example.com-cert.pem"

    infoln "Generating the ${ORDERER} TLS certificates, use --csr.hosts to specify Subject Alternative Names"
    set -x
    fabric-ca-client enroll -u https://${ORDERER}:${ORDERER}pw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls" --enrollment.profile tls --csr.hosts ${ORDERER}.example.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
    { set +x; } 2>/dev/null

    # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/ca.crt"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/server.crt"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/server.key"

    # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
    mkdir -p "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/tlscacerts"
    cp "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/example.com/orderers/${ORDERER}.example.com/msp/tlscacerts/tlsca.example.com-cert.pem"
  done

  # Register and generate artifacts for the orderer admin
  infoln "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  infoln "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/example.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/example.com/users/Admin@example.com/msp/config.yaml"
}
