version: "3.6"

networks:
    docker_test:
        external: true

services:
    asset-transfer-basic.Rbi.example.com:
        build: .
        container_name: asset-transfer-basic.Rbi.example.com
        hostname: asset-transfer-basic.Rbi.example.com
        volumes:
            - ./crypto:/crypto
        env_file:
            - chaincode1.env
        networks:
            docker_test:
        expose:
            - 9999

    asset-transfer-basic.Hdfc.example.com:
        build: .
        container_name: asset-transfer-basic.Hdfc.example.com
        hostname: asset-transfer-basic.Hdfc.example.com
        volumes:
            - ./crypto:/crypto
        env_file:
            - chaincode2.env
        networks:
            docker_test:
        expose:
            - 9999
