#
# SPDX-License-Identifier: Apache-2.0
#
---
- name: Commit chaincode
  hosts: localhost
  vars:
    wallet: "/_cfg"
  vars_files:
    - /_cfg/asset-transfer-chaincode-vars.yml
    - /_cfg/fabric-common-vars.yml
    - /_cfg/fabric-Rbi-vars.yml
    - /_cfg/auth-vars.yml
  tasks:
    - name: Commit the chaincode on the channel
      ibm.blockchain_platform.committed_chaincode:
        api_endpoint: "{{ api_endpoint }}"
        api_authtype: "{{ api_authtype }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret | default(omit) }}"
        api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
        peer: "{{ Rbi_peer_name }}"
        identity: "{{ wallet }}/{{ Rbi_name }} Admin.json"
        msp_id: "{{ Rbi_msp_id }}"
        channel: "{{ channel_name }}"
        organizations:
          - "{{ Rbi_name }}"
          - "{{ Hdfc_name }}"
        name: "{{ smart_contract_name }}"
        version: "{{ smart_contract_version }}"
        sequence: "{{ smart_contract_sequence }}"
        endorsement_policy: "{{ smart_contract_endorsement_policy | default(omit) }}"
        collections_config: "{{ smart_contract_collections_file | default(omit) }}"
